"""add_supplier_analysis_table

Revision ID: 50a2db73d1a0
Revises: 95dbdb6d36fa
Create Date: 2026-02-01 14:51:46.110797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a2db73d1a0'
down_revision = '95dbdb6d36fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('nc_codes', sa.JSON(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('annual_volume', sa.Float(), nullable=True),
    sa.Column('regulatory_risks_count', sa.Integer(), nullable=True),
    sa.Column('regulatory_risks', sa.JSON(), nullable=True),
    sa.Column('weather_risks_count', sa.Integer(), nullable=True),
    sa.Column('weather_risks', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_analyses')
    # ### end Alembic commands ###
