"""initial_schema_with_weather_alerts

Revision ID: 95dbdb6d36fa
Revises: 
Create Date: 2026-02-01 13:06:11.282811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dbdb6d36fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('headquarters_country', sa.String(length=100), nullable=False),
    sa.Column('total_sites', sa.Integer(), nullable=True),
    sa.Column('total_suppliers', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('data_sources_config', sa.JSON(), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_subtype', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('geographic_scope', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_sha256')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hutchinson_sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('raw_materials', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_production_value', sa.Float(), nullable=True),
    sa.Column('strategic_importance', sa.String(length=20), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('products_supplied', sa.JSON(), nullable=False),
    sa.Column('company_size', sa.String(length=20), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('financial_health', sa.String(length=20), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('site_criticality', sa.String(length=20), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supply_chain_risk', sa.Text(), nullable=False),
    sa.Column('forecast_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_truth_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('expert_pertinence_decision', sa.String(length=20), nullable=False),
    sa.Column('expert_pertinence_reasoning', sa.Text(), nullable=False),
    sa.Column('expert_risk_level', sa.String(length=20), nullable=False),
    sa.Column('expert_affected_sites', sa.JSON(), nullable=True),
    sa.Column('expert_affected_suppliers', sa.JSON(), nullable=True),
    sa.Column('expert_recommendations', sa.Text(), nullable=False),
    sa.Column('expert_name', sa.String(length=200), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('pertinence_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('matched_elements', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('supplier_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hutchinson_site_id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('products_supplied', sa.JSON(), nullable=False),
    sa.Column('annual_volume', sa.Float(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('is_sole_supplier', sa.Boolean(), nullable=True),
    sa.Column('has_backup_supplier', sa.Boolean(), nullable=True),
    sa.Column('backup_supplier_id', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('risk_mitigation_plan', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['backup_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['hutchinson_site_id'], ['hutchinson_sites.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('pertinence_check_id', sa.String(), nullable=False),
    sa.Column('impacts_description', sa.Text(), nullable=False),
    sa.Column('affected_sites', sa.JSON(), nullable=True),
    sa.Column('affected_suppliers', sa.JSON(), nullable=True),
    sa.Column('geographic_analysis', sa.JSON(), nullable=True),
    sa.Column('criticality_analysis', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('supply_chain_impact', sa.String(length=20), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['pertinence_check_id'], ['pertinence_checks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    sa.UniqueConstraint('pertinence_check_id')
    )
    op.create_table('ground_truth_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ground_truth_case_id', sa.String(), nullable=False),
    sa.Column('pertinence_check_id', sa.String(), nullable=False),
    sa.Column('risk_analysis_id', sa.String(), nullable=False),
    sa.Column('pertinence_match', sa.Boolean(), nullable=False),
    sa.Column('risk_level_match', sa.Boolean(), nullable=False),
    sa.Column('sites_match_score', sa.Float(), nullable=False),
    sa.Column('suppliers_match_score', sa.Float(), nullable=False),
    sa.Column('overall_match_score', sa.Float(), nullable=False),
    sa.Column('discrepancies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_truth_case_id'], ['ground_truth_cases.id'], ),
    sa.ForeignKeyConstraint(['pertinence_check_id'], ['pertinence_checks.id'], ),
    sa.ForeignKeyConstraint(['risk_analysis_id'], ['risk_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judge_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('risk_analysis_id', sa.String(), nullable=False),
    sa.Column('score_completeness', sa.Float(), nullable=False),
    sa.Column('score_accuracy', sa.Float(), nullable=False),
    sa.Column('score_relevance', sa.Float(), nullable=False),
    sa.Column('score_clarity', sa.Float(), nullable=False),
    sa.Column('score_actionability', sa.Float(), nullable=False),
    sa.Column('score_traceability', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_analysis_id'], ['risk_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_analysis_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('risk_analysis_id', sa.String(), nullable=False),
    sa.Column('judge_evaluation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('affected_sites', sa.JSON(), nullable=True),
    sa.Column('affected_suppliers', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['judge_evaluation_id'], ['judge_evaluations.id'], ),
    sa.ForeignKeyConstraint(['risk_analysis_id'], ['risk_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('alerts')
    op.drop_table('judge_evaluations')
    op.drop_table('ground_truth_results')
    op.drop_table('risk_analyses')
    op.drop_table('supplier_relationships')
    op.drop_table('pertinence_checks')
    op.drop_table('ground_truth_cases')
    op.drop_table('weather_alerts')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('hutchinson_sites')
    op.drop_table('execution_logs')
    op.drop_table('documents')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
