"""add_extra_metadata_to_supplier_analyses

Revision ID: af4473498229
Revises: 50a2db73d1a0
Create Date: 2026-02-01 15:58:52.827359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4473498229'
down_revision = '50a2db73d1a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_analyses', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_analyses', 'extra_metadata')
    # ### end Alembic commands ###
